---
title: Sense HAT smile
hero_image: images/banner.png
description: Leer met Python sensorgegevens lezen van de Sense HAT en hoe je met pixelillustraties op de Sense HAT werkt
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Inleiding
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: And breathe...
