---
title: Laat een Sense l HAT glimlachen met behulp van sensoren
hero_image: afbeeldingen / banner.png
description: Leer met Python sensorgegevens lezen van de Sense HAT en hoe je pixelillustraties op de de SENS HAT aanstuurt
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmeren-0, computeren-0
interests: "computergebruik"
technologies: "sense-hat, computergebruik, python"
site_areas: ""
steps:
  - 
    title: Intruductie
  - 
    title: Wat heb je nodig
  - 
    title: Test de Sense HAT
  - 
    title: gezichten
  - 
    title: En adem...
