title: Make a Sense HAT smile with sensors
hero_image: images/cover.png
description: Learn to read sensor data from the Sense HAT using Python, and how to use pixel art on the Sense HAT's pixel display
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: "physical computing"
technologies: "sense-hat, physical computing, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Test the Sense HAT
  - title: Faces
  - title: And breathe...
