---
title: Make a Sense HAT smile with sensors
hero_image: images/cover.png
description: Pythonを使用してSense HATからセンサーデータを読み取る方法、Sense HATのピクセル表示でピクセルアートを使用する方法
theme: 赤
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: sense-hat, electronic-components, python
site_areas: jam
hardware: sense-hat, electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: センスHATをテストする
  - 
    title: 顔
  - 
    title: そして...
