---
title: Направете чувство на усмивка HAT с сензори
hero_image: images/cover.png
description: Научете се да четете сензорни данни от Sense HAT, използвайки Python, и как да използвате пикселно изкуство в пикселния дисплей на Sense HAT
theme: червен
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: sense-hat, electronic-components, python
site_areas: jam
hardware: sense-hat, electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Въведение
  - 
    title: Какво ще ви трябва
  - 
    title: Тествайте Sense HAT
  - 
    title: Faces
  - 
    title: И дишайте ...
