---
title: Bringe mit Sensoren ein Sense-HAT zum Lächeln
hero_image: images/cover.png
description: Lerne, wie du mit Python Sensordaten aus dem Sense HAT lesen kannst und wie du Pixel-Art auf der Pixelanzeige des Sense HAT verwendest
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: sense-hat, electronic-components, python
site_areas: jam
hardware: sense-hat, electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Teste das Sense-HAT
  - 
    title: Gesichter
  - 
    title: Und atme ...
