---
title: Sense HAT mosoly
hero_image: images/banner.png
description: Tanuld meg, hogyan olvashatod a Sense HAT érzékelő adatait Python használatával és hogyan hozz létre pixel műveket a Sense HAT pixel kijelzőjén
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Bevezetés
  - 
    title: Teszteld a Sense HAT-et
  - 
    title: Arcok
  - 
    title: És lélegezz...
