---
title: Hozz létre egy érzéket HAT mosolyt érzékelőkkel
hero_image: images/cover.png
description: Olvassa el a Sense HAT szenzor adatait a Python segítségével, és hogyan használja a képpontot a Sense HAT képpont kijelzőjén
theme: piros
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: sense-hat, electronic-components, python
site_areas: jam
hardware: sense-hat, electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: Tesztelje a Sense HAT-ot
  - 
    title: arcok
  - 
    title: És lélegezz ...
