---
title: Sense HAT smile
hero_image: images/banner.png
description: Olvassa el a Sense HAT szenzor adatait a Python segítségével, és hogyan használja a képpontot a Sense HAT képpont kijelzőjén
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Bevezetés
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: And breathe...
