---
title: Sourire Sense HAT
hero_image: images/banner.png
description: Apprend à lire les données des capteurs du Sense HAT avec Python et à afficher de l'art pixel sur l'affichage du Sense HAT
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introduction
  - 
    title: Tester le Sense HAT
  - 
    title: Visages
  - 
    title: Et respirez...
