---
title: Faites sourire le Sense HAT avec ses capteurs
hero_image: images/banner.png
description: Apprenez à lire les données des capteurs du Sense HAT avec Python et à afficher de l'art pixel sur l'affichage du Sense HAT
theme: rouge
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "sense-hat, physical computing, python"
site_areas: ""
steps:
  - 
    title: introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Testez le Sense HAT
  - 
    title: Visages
  - 
    title: Et respire ...
