---
title: Sense HAT smile
hero_image: images/banner.png
description: Apprenez à lire les données des capteurs du Sense HAT avec Python et à afficher de l'art pixel sur l'affichage du Sense HAT
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introduction
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: And breathe...
