---
title: Faire sourire Sense HAT à l'aide de capteurs
hero_image: images/cover.png
description: Apprenez à lire les données des capteurs du Sense HAT en utilisant Python, et à utiliser le pixel art sur l'écran d'affichage de pixels du Sense HAT
theme: rouge
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: sense-hat, electronic-components, python
site_areas: jam
hardware: sense-hat, electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: Testez le Sense HAT
  - 
    title: Visages
  - 
    title: Et respire ...
