---
title: Le sourire du Sense HAT
hero_image: images/banner.png
description: Apprenez à lire les données des capteurs du Sense HAT en utilisant Python, et à utiliser le pixel art sur l'écran d'affichage de pixels du Sense HAT
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: introduction
  - 
    title: Teste le Sense HAT
  - 
    title: Visages
  - 
    title: Et respire...
