---
title: Faire sourire Sense HAT à l'aide de capteurs
hero_image: images / banner.png
description: Apprenez à lire les données des capteurs du Sense HAT en utilisant Python, et à utiliser le pixel art sur l'écran d'affichage de pixels du Sense HAT
theme: rouge
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "informatique physique"
technologies: "sense-hat, informatique physique, python"
site_areas: ""
steps:
  - 
    title: introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: Testez le Sense HAT
  - 
    title: Visages
  - 
    title: Et respire ...
