---
title: Faire un sourire de sens HAT avec des capteurs
hero_image: images / banner.png
description: Apprenez à lire les données des capteurs du Sense HAT en utilisant Python, et comment utiliser pixel art sur l'affichage des pixels du Sense HAT
theme: rouge
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmation-0, phys-comp-0
interests: "informatique physique"
technologies: "sense-hat, informatique physique, python"
site_areas: ""
steps:
  - 
    title: introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Testez le Sense HAT
  - 
    title: Visages
  - 
    title: Et respire ...
