---
title: Sense HAT smile
hero_image: images/banner.png
description: Imparare a leggere i dati forniti dai sensori del Sense HAT usando Python, e come usare la pixel art sul display del Sense HAT
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: introduzione
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: And breathe...
