---
title: Fai sorridere il Sense HAT con i sensori
hero_image: images/cover.png
description: Imparare a leggere i dati forniti dai sensori del Sense HAT usando Python, e come usare la pixel art sul display del Sense HAT
theme: rosso
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: sense-hat, electronic-components, python
site_areas: jam
hardware: sense-hat, electronic-components
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: introduzione
  - 
    title: Cosa ti serve
  - 
    title: Prova il Sense HAT
  - 
    title: Le espressioni facciali
  - 
    title: E respira...
