---
title: Fai sorridere il Sense HAT con i sensori
hero_image: images/banner.png
description: Imparare a leggere i dati forniti dai sensori del Sense HAT usando Python, e come usare la pixel art sul display del Sense HAT
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "sense-hat, physical computing, python"
site_areas: ""
steps:
  - 
    title: introduzione
  - 
    title: Cosa ti serve
  - 
    title: Prova il Sense HAT
  - 
    title: Le espressioni facciali
  - 
    title: E respira...
